### ISSUE TITLE
fMRI bandpass filter artifacts

### ISSUE THREAD

**Issue by koenhelwegen** [dutchconnectomelab/CATO#27]
When applying a bandpass filter in the functional pipeline, we sometimes observe artifacts in the beginning and/or end of the timeseries. @SiemondeLange and I looked into this and noticed that matlabs [`filtfilt`](https://nl.mathworks.com/help/signal/ref/filtfilt.html) function matches the initial and final few timepoints of the filtered signal to the unfiltered signal. For our use case this is undesirable, as the amplitude of the high-frequency signal that is removed during filtering is higher than the mid-frequency signal that is retained; matching the initial/final signal causes the observed artifacts.

<img src="https://user-images.githubusercontent.com/29484762/213156416-b1de60d0-6e91-4160-8095-ad171a36460f.png" width=50% height=50%>

To solve this, we will avoid the use of `filtfilt` and apply the filter directly.

**Comment by koenhelwegen** [comment]
A secondary issue was introduced by the mirror filtering. In the current implementation, the signal is mirrored both vertically and horizontally 'around' the first and last point. However, if the signal is highly erratic, there is a high probability this mirroring creates jumps (example on the right in image).

<img src="https://user-images.githubusercontent.com/29484762/213193029-6cb6d644-9c45-4858-ba32-ca9bbb5df876.png" width=50% height=50%>

It appears that for our use case only mirroring in the time dimension is better.

**Comment by koenhelwegen** [comment]
I compared the current solution as implemented in #28 to [Gustafsson's method](https://ieeexplore.ieee.org/abstract/document/492552) that is available in [`scipy.signal.filtfilt`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.filtfilt.html). Note that this method is referenced in the MATLAB `filtfilt` documentation but it appears it is not actually implemented (see also [here](https://dsp.stackexchange.com/questions/37619/zero-phase-filter-determining-initial-conditions-for-forward-backward-filtering)).

Here are the various options side by side for a few voxels:

<img src="https://user-images.githubusercontent.com/29484762/216637109-eaef78c2-9163-41ea-b404-8b5212718275.png" width=45% height=45%>
<img src="https://user-images.githubusercontent.com/29484762/216637879-06ceaa3c-8316-4659-a9a3-ca737244eaa2.png" width=45% height=45%>
<img src="https://user-images.githubusercontent.com/29484762/216638429-67566ff4-55d7-436a-be9b-69c5dfa997b9.png" width=45% height=45%>

If I compute the within-voxel absolute z-scores and then average over all voxels to get a rough metric of how 'exceptional' the timeseries are at the edges, I get for this particular subject:

![image](https://user-images.githubusercontent.com/29484762/216639740-c7fecfb2-3fd2-497e-9292-aa4daa3e0d68.png)

Based on this I don't have a preference for either method. However, I couldn't find a clean implementation of Gustafsson's method for MATLAB, and I would rather avoid implementing our own version, so based on this I suggest we keep the fix as in #28.

**Comment by SiemondeLange** [comment]
Thank you for analyzing and comparing the different methods! I agree with the proposed solution of padding the signal using the the time-mirrored timeseries. This method is might not be perfect, as indicated by the small bumps still visible in the mean absolute z-score plot, but it provides a good balance between retaining as many time points in the analysis and having a well-filtered signal. I will merge #28 into the main branch and release a new update for CATO.
